### ISSUE TITLE
Login with default credentials does not work with 0.9.4

### ISSUE THREAD

**Issue by ntimo** [gregtwallace/legocerthub#10]
## Issue
After installting 0.9.4 the default login with `admin`:`password` does not work.

## Workarround
After downgrading to 0.9.3 it works.

**Comment by gregtwallace** [comment]
What environment is this in?  And was it a completely fresh install?

**Comment by ntimo** [comment]
Yes it was a completely fresh install, on Ubuntu 22.04 via a systemd service

**Comment by gregtwallace** [comment]
I can’t reproduce this and the code responsible for setting up the DB hasn’t changed in a few versions. Can you try it again?

**Comment by gregtwallace** [comment]
Insufficient information.
