### ISSUE TITLE
[feat] Support for subpath for reverse proxies

### ISSUE THREAD

**Issue by xorguy** [gregtwallace/legocerthub#12]
Hi.

For those only using DNS challenge a subpath support will help to serve the app under same domain as others applications, no need to use a subdomain.
Right now the application loads http://mylegocert/app, it will help to allow to set a subpath so application can load in URL like https://my_reverse_proxy_server/legocerthub/app.

**Comment by gregtwallace** [comment]
I went down this road a little bit in the past.  The backend this is super easy to implement.  However, React is a roadblock.

Specifically, when the frontend builds, the paths are hard coded.  There is no easy way to modify the base path at runtime.  The only idea I currently have that might work is replacing all of the paths in the frontend files every time LeGo launches but that sounds like quite a manual mess which would likely make it error prone.

Alternatively, I could change the default path to always include /legocerthub first, but I'm not sure I'm in love with that idea.

If you have any React expertise I'm all ears.  I've searched a lot and tried a number of different methods but all roads seem to lead back to those darn hardcoded paths.

**Comment by xorguy** [comment]
Hi.

Because I have no expertise on React I was just wondering if it was feasible, even if I was able to try I would give a try but I don't know how.

Anyway thanks for the app!

Regards.

**Comment by gregtwallace** [comment]
I made the changes to add the path /legocerthub (no option to change it). I’m still debating on merging. The issue is it would require all client scripts to be updated to query the correct api end point (with the additional path). 

Current inclination is to just do it but we’ll see.

**Comment by gregtwallace** [comment]
I realized I can just add some redirects to provide backwards compatibility.  I'll get this added.

**Comment by xorguy** [comment]
Hi, tried latest docker version and even accessing by IP and port, not reverse proxy, the URL that loads is redirected to: http://ip:4050/legocerthub/legocerthub.

Seems is adding a second legocerthub.

Is any config to alter that for when is running under reverse proxy or direct?

**Comment by gregtwallace** [comment]
I can’t test right now but have you tried in a private browser window? And/or clear cache?

**Comment by gregtwallace** [comment]
https://github.com/gregtwallace/legocerthub/issues/15
