### ISSUE TITLE
Cloudflare DNS provider issue

### ISSUE THREAD

**Issue by mhhakim** [gregtwallace/legocerthub#14]
Hi,
I am having issue on configuring Cloudflare DNS challenge as provider. When I use “account” credential (email & global key), it works fine. But when I try to configure using API token, I get the following error.
<pre>
error	challenges/service.go:131	failed to configure dns 01 cloudflare (cloudflare config error: no domains (zones) found)
error	app/run.go:271	failed to configure app challenges (cloudflare config error: no domains (zones) found)
error	app/run.go:40	failed to create app (cloudflare config error: no domains (zones) found)
</pre>

My API token is fine, I checked by making direct curl request to Cloudflare API endpoint. Here is the config format I am using:

<pre>
# Challenge Providers
challenges:
  dns_checker:
    skip_check_wait_seconds: null
    dns_services:
      - primary_ip: 1.1.1.1
        secondary_ip: 1.0.0.1
      - primary_ip: 9.9.9.9
        secondary_ip: 149.112.112.112
      - primary_ip: 8.8.8.8
        secondary_ip: 8.8.4.4
  providers:
    http_01_internal:
      enable: false
      port: 81
    dns_01_cloudflare:
      enable: true
      tokens:
        - api_token: API_Token
          zone_names:
            - domain.tld
</pre>

Any help is appreciated.

Thanks

**Comment by gregtwallace** [comment]
I found the problem . I'm sorry, the sample config has a typo in the yaml.

`tokens` should be `api_tokens`

e.g.

    dns_01_cloudflare:
      enable: true
      **api_tokens:**
        - api_token: API_Token
          zone_names:
            - domain.tld
