### ISSUE TITLE
error when try default auth

### ISSUE THREAD

**Issue by devzwf** [gregtwallace/legocerthub#2]
geting this when i am trying the default username/password
![lego](https://user-images.githubusercontent.com/25246962/235525394-a6a360d7-50cd-4483-bc0f-2f8cbe407edf.PNG)

will try debug log to see.

**Comment by gregtwallace** [comment]
This means the backend did not respond for some reason.  Open up browser console, you should see more details.  Also, check the file located at /app/env.js  There should be an API URL that matches the box you're running on.  e.g. https://some.example.com:443/api

Make sure 'hostname' is properly set in the config.yaml

**Comment by devzwf** [comment]
ok i see 
`Failed to load resource: net::ERR_NAME_NOT_RESOLVED`

i will check what i can fix 
and will update

**Comment by devzwf** [comment]
Oh and i could not found the env.js

**Comment by gregtwallace** [comment]
Insufficient details.  Try the new version though.  The config file changed a little in 0.8.0 and might fix your issue.
