### ISSUE TITLE
Extend the list of dns providers

### ISSUE THREAD

**Issue by Parlendir** [gregtwallace/legocerthub#21]
Hello, 

Legocerthib manages the following dns providers:

https://github.com/acmesh-official/acme.sh/wiki/dnsapi

Other projects using let's encrypt offer this list of providers: 

https://go-acme.github.io/lego/dns/#dns-providers

(example: https://github.com/azukaar/cosmos-Server/#let's-encrypt) 

The provider I'm looking to use is freemyip.com, which is present in the second list but not the first. 

Would it be possible to extend the list of dns providers supported by Legocerthub?

**Comment by gregtwallace** [comment]
I will continue to update with new versions of acme.sh but trying to support everyone is difficult.  The best suggestion I can give for now is to use a manual script if your provider isn't included.

If you're feeling really frisky, write a script for acme.sh and send them a pull request.
