### ISSUE TITLE
Please open discussions for this project

### ISSUE THREAD

**Issue by noseshimself** [gregtwallace/legocerthub#26]
I'm not completely convinced about the architecture but before adding a metric ton of feature requests it might be better to have a separate place to discuss these things first. That list would include pushing certificates to clients instead of polling, DNS configuration per domain (? a concept not even showing up in the front end) or functions like adding/deleting domain names to/from certificates.

I don't think that these things should be part of the config.yaml file either...

**Comment by gregtwallace** [comment]
Discussion forum has been launched. 

https://forum.legocerthub.com/
