### ISSUE TITLE
Issue with config file (providers)

### ISSUE THREAD

**Issue by mp3-10** [gregtwallace/legocerthub#27]
Hello,

I used default config file (from: [https://github.com/gregtwallace/legocerthub-backend/blob/master/config.default.yaml](url)) but I have still errors like:
`2023-10-10T12:03:05.508Z        error   app/run.go:63   failed to create app (yaml: unmarshal errors:
line 49: cannot unmarshal !!seq into http01internal.Config
line 54: cannot unmarshal !!seq into dns01acmesh.Config)`

Both lines points `- 'domains':` section.

Part of my code:

```
  'providers':
    # If any provider is configured, the default will not be
    'http_01_internal':
      - 'domains':
          - '*'
        'port': 4060

    'dns_01_acme_sh':
      - 'domains':
          - 'XXX.XXX'
        'environment':
          - 'OVH_END_POINT=ovh-eu'
          - 'OVH_AK=XXX'
          - 'OVH_AS=XXX'
          - 'OVH_CK=XX'
        'dns_hook': 'dns_ovh'

```

**Comment by gregtwallace** [comment]
The new release I’m working on uses a different config file format which is not compatible with older versions. Use the example included in the release package or change the GitHub code you’re browsing to the Tag for the version you’re using.

**Comment by mp3-10** [comment]
@gregtwallace my fault. Now is ok, thx! But could you add **openssl** into docker file?

Without: 
`./scripts/acme.sh/temp/acme.sh_dns_ovh.sh: line 1006: openssl: command not found`

On my docker I installed and now works well :)

**Comment by gregtwallace** [comment]
I will add that, thanks for the heads up.
