### ISSUE TITLE
Config option for theme

### ISSUE THREAD

**Issue by ntimo** [gregtwallace/legocerthub#30]
Hello Greg,
just a minor suggestion, it would be really cool to be able to configure the theme via the config, so the default theme color is dark.

Best wishes,
Timo

**Comment by gregtwallace** [comment]
The default theme is already set based on the client’s preference using a media query. 

https://github.com/gregtwallace/legocerthub-frontend/blob/master/src/context/ThemeProvider.jsx

**Comment by gregtwallace** [comment]
This is already covered by the media query.
