### ISSUE TITLE
OCSP support

### ISSUE THREAD

**Issue by ntimo** [gregtwallace/legocerthub#31]
Hello,
currently I can't find a way to issue a cert with ocsp enabled. Could you maybe take a look into adding this feature to LeGo.

thanks and best wishes,
Timo

**Comment by gregtwallace** [comment]
I’m not overly familiar with this subject but OCSP is implemented by the client.  If you mean stapling, I think that’s configured on the server. 

Are you talking about the “must staple” option?

**Comment by ntimo** [comment]
Yes I mean the „must staple“ option. Currently it’s not possible to have LeGo add this to a cert.

**Comment by gregtwallace** [comment]
I might look into a more generic solution to this.  Possibly an advanced CSR configuration section where any extension could be added.

**Comment by gregtwallace** [comment]
Extra extensions, including the ability to add the Must Staple extension will be in the next release.

See: https://github.com/gregtwallace/legocerthub-backend/commit/168b71d9f9674e36822575bf69ed5655f1f7119c
