### ISSUE TITLE
No acme account in certificate page

### ISSUE THREAD

**Issue by mauvray** [gregtwallace/legocerthub#33]
When setting up the app, I created an ACME Account and when I moved to the certificate creation, the ACME Account list is empty. I don't see anything inside the logs (even in debug).

Here is the ACME Accounts view
![image](https://github.com/gregtwallace/legocerthub/assets/47172756/03d31bfb-a6a6-4587-8c49-dd0062af9c67)
Here is the Certificate creation view
![image](https://github.com/gregtwallace/legocerthub/assets/47172756/bb140b2f-12c9-4146-944b-b11d1eca78c9)

I am running legocerthub with the latest docker image

**Comment by gregtwallace** [comment]
Thanks for the screenshots. You have to register the account before you can use it. This is why the status is listed as "Unknown". Just click on the account in the Accounts page and there is a "Register" button in the account screen.

<img width="441" alt="Untitled" src="https://github.com/gregtwallace/legocerthub/assets/63136063/b839acc4-cf20-4bca-8ec3-584cd267f9b2">

**Comment by gregtwallace** [comment]
If this isn't the issue, please re open and provide logs from when you push the button.
