### ISSUE TITLE
Provider selection should select longest matching domain

### ISSUE THREAD

**Issue by ruifung** [gregtwallace/legocerthub#40]
For example, I have domain.example which is using the cloudflare provider, but subdomain.domain.example is delegated to a local nameserver (via NS records) which is configured with using the shell provider to perform updates using RFC2136.

I have observed legocerthub using the cloudflare provider instead of the shell provider to perform it's validations, this results in the validation stalling indefinitely because as the subdomain is delegated via NS records, the TXT records set on cloudflare are non-resolvable.

In this case, I believe it should select the provider with the longest matching domain as that will be the zone the records should be inserted to.

**Comment by gregtwallace** [comment]
I had not considered such a use case, but this should be pretty easy to adjust.
