### ISSUE TITLE
HTTPS port not enabled by default?

### ISSUE THREAD

**Issue by aj0413** [gregtwallace/legocerthub#46]
Feels like I’m missing something obvious, but I thought HSTS and HTTPS port 4055 were enabled by default.

Deployed service via Portainer and can only connect via HTTP on 4050. Checked the config default and example files, but may just be me missing something obvious (haven’t had time to dig in and troubleshoo)t ?

**Comment by gregtwallace** [comment]
Have you created a certificate? It won’t run as https until a certificate is created for it to use.

**Comment by gregtwallace** [comment]
Is it named legocerthub or did you change the config to the name of the certificate if it isn’t that name?

if you’ve done that, I’ll  debug logs.

**Comment by aj0413** [comment]
ahhh, I hadn’t realized the service would care. I thought the cert name just needed to match the host name used to connect. Let me try that and get back to you
