### ISSUE TITLE
[feat] Allow User-Defined Password Options

### ISSUE THREAD

**Issue by PasserDreamer** [gregtwallace/legocerthub#7]
By default, it cannot be set to less than 10 characters.
It would be great if there were an option to change it, as not every scenario has such strong requirements.

**Comment by gregtwallace** [comment]
Even 10 character with no other requirement is pretty weak considering the security risk of a compromise. 

That said, if you insist on worse, dev mode disables the requirement. Toggle it on, change password, toggle back off.

**Comment by gregtwallace** [comment]
I adjusted the min length to 8 and added comments regarding devMode.
